# Site settings
title: Jekyll Template
author: Name # of sole author or company
email: email@domain.com
description: A Jekyll Template created by Seemingly Creative
url: 'http://template.daveas.github.io'
icon: /assets/images/icon.png
social_name: replace
google_analytics: replace
disqus: replace
credits: Seemingly Creative


# Build settings
markdown: kramdown
permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
gems:
  - jemoji
  - jekyll-sitemap
